// Created by larobinson, 2024
// Copyright Bungie, Inc.

export enum AreaNames {
  Admin = "Admin",
  Application = "Application",
  BeyondLight = "BeyondLight",
  BungieTech = "BungieTech",
  Clan = "Clan",
  Clans = "Clans",
  Codes = "Codes",
  Collections = "Collections",
  CrossSave = "CrossSave",
  Destiny = "Destiny",
  Direct = "Direct",
  Emails = "Emails",
  FireteamFinder = "FireteamFinder",
  Fireteams = "Fireteams",
  Guide = "Guide",
  Legal = "Legal",
  Marathon = "Marathon",
  News = "News",
  Newsroom = "Newsroom",
  ParentalControlsLanding = "ParentalControls",
  Pgcr = "Pgcr",
  Registration = "Registration",
  Rewards = "Rewards",
  Search = "Search",
  Seasons = "Seasons",
  Static = "Static",
  Sms = "Sms",
  Triumphs = "Triumphs",
  User = "User",
  UserResearch = "UserResearch",
}
