name: Scheduled checks

on:
  push:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check-run-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - run: yarn install

      - name: Check Bungie website
        run: yarn run check
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Check if there were changes
        id: changes-check
        run: echo ::set-output name=changes::"$(git status --porcelain | wc -l)"

      - name: Commit everything
        if: steps.changes-check.outputs.changes > 1
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add **/*.scss
          git commit -m "SCSS changed from automated check" || true
          git add .
          git commit -m "Site changed from automated check" || true

      - name: Push changes
        if: steps.changes-check.outputs.changes > 1
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
